apiVersion: v1
kind: Service
metadata:
  # labels for the service
  labels:
    name: rfcweb
  # name of the service
  name: rfcweb
spec:
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    # select Deployments with the name "rfcweb"
    name: rfcweb
---
# Kubernetes API version
apiVersion: extensions/v1beta1
# Type of "request"
kind: Deployment
# Metadata of the "object"
metadata:
  # Name of the "object"
  name: rfcweb
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: rfcweb

    spec:
  # List of Container definitions
      containers:
    # What Docker image to use
        - image: 1739582/rfcweb:#{Build.BuildId}#
      # The "name"/"suffix" of the container name
          name: rfcweb
      # List of environment variables
          env:
            - name: WORDPRESS_DB_HOST
              value: rabii2.mysql.database.azure.com
            - name: WORDPRESS_DB_NAME
              value: wp-db
            - name: WORDPRESS_DB_PASSWORD
              value: Aze123rty123
            - name: WORDPRESS_DB_USER
              value: rabii2@rabii2
      # List of ports to "publish"
          ports:
        # ContainerPort exposes only to the inside of your network, not to the outside
        # To reach the container we create a cluster wide service
            - containerPort: 80
          # gives the port a name
              name: rfcweb

